export const toolbarOptions = [
  [{ header: [1, 2, 3, 4, 5, 6] }, { font: [] }],
  [{ size: [] }],
  ["bold", "italic", "underline", "strike", "blockquote"],
  [{ align: [] }],
  [{ list: "ordered" }, { list: "bullet" }, { indent: "-1" }, { indent: "+1" }],
  ["link", "image", "video"],
  ["code-block"],
  ["clean"],
];

export const formats = [
  "header",
  "font",
  "size",
  "bold",
  "italic",
  "underline",
  "strike",
  "blockquote",
  "list",
  "bullet",
  "align",
  "indent",
  "link",
  "image",
  "video",
  "code-block",
  "height",
  "width",
  "float",
  "style",
  "display",
  "margin",
];
